- name: install package
  hosts: remote
  become: true
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
       src: index.html
       dest: /root/foo.conf
       owner: root
       group: root
       mode: '0644'
    register: copy_result
    ignore_errors: yes
    failed_when: false
    notify: Propmt user to place index.html
  handlers:
  -name:     
         

